apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhaneesh-deployment
  labels:
    app: my-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: my-webapp
        image: dhaneeshdharun/dharun:latest
        ports:
         - containerPort: 8080
