apiVersion: v1
kind: Service
metadata:
  name: dhaneesh-service
spec: 
  selector:
    app: my-webapp
  type: NodePort
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
     nodePort: 30081